### ISSUE TITLE
Peerdeps has invalid ranges for Effect-TS packages

### ISSUE THREAD

**Issue by XiNiHa** [iamchanii/pothos-plugin-effect#1]
Since the Effect-TS packages are currently at 0.x version, minor version bumps can break the interface.
And it's actually happening right now (the latest version of `@effect/io` provides a new interface for `Effect.Do` and it's breaking the plugin since the plugin is expecting the old interface)
I'd suggest you lock down the minor version of Effect-TS peer dependencies, rather than marking every 0.x version as usable.

**Comment by iamchanii** [comment]
Gotcha... sometimes I imagined about it, but it comes true. I will release soon about fix to peer-deps to `^0.12` and `^0.30`.
