### ISSUE TITLE
Integration with the prisma plugin

### ISSUE THREAD

**Issue by devunt** [iamchanii/pothos-plugin-effect#17]
Is there a way to integrate pothos [prisma plugin](https://pothos-graphql.dev/docs/plugins/prisma) with pothos-plugin-effect? We heavily use prisma plugin's query optimization feature, so it would be lovely to see both plugin work in action.

**Comment by iamchanii** [comment]
Agree it will be so nice feature. I just started imagiation about `t.prismaEffect`, what do you want to do using pothos-plugin-effect supports prisma plugin intetgration?

**Comment by iamchanii** [comment]
@devunt I opened a pr for this. check out test cases and let me know it is enough for your cases or not.

https://github.com/iamchanii/pothos-plugin-effect/blob/29d4709889d614ca68c07e3c8736371eb583fa5c/src/tests/integrate-prisma.test.ts
