### ISSUE TITLE
Improve prisma integration

### ISSUE THREAD

**Issue by iamchanii** [iamchanii/pothos-plugin-effect#21]
- [x] Add prisma generator

```prisma 
generator effect {
  provider = "..."
}
```

- [x] Provide generated context
```ts
declare const Prisma: Context.Tag<EffectPrisma>;

// $ExpectType Effect.Effect<never, PrismaError, User>
Prisma.user.findUniqueOrThrow({ ... })
```

- [x] Provide PothosEffectPrismaClient tag 
- [x] #25
- [ ] I think ts-morph is too heavy. should I replace it to typescript?

**Comment by Enalmada** [comment]
@iamchanii [effect usage](https://www.npmjs.com/package/effect) seems to be growing rapidly.  While trying to help update effect dependency, I noticed code to support prisma right next to code to support effect.  

Although I loved using prisma in the past, I am working on a drizzle project now wonder if one way to "improve prisma integration" would be to create a monorepo here with `pothos-plugin-effect` being a base plugin for people using neither prisma or drizzle and then having a separate `pothos-plugin-effect-prisma` plugin to optionally add on prisma functionality.  In the near future perhaps there could be a `pothos-plugin-effect-drizzle` that could pattern after the prisma code without impacting the effect code.

Thoughts?

**Comment by iamchanii** [comment]
@Enalmada Good idea. but the Prisma integration was possible because the plugin already existed in Pothos. `pothos-plugin-effect` is just glue-ing pothos with effect. if pothos supports drizzle offically, I can consider about it.

**Comment by iamchanii** [comment]
@Enalmada As of 1.0, `t.effect` can resolve Promise without using Effect.tryPromise, so drizzle (also prisma) can be used directly in Effect.

https://github.com/iamchanii/pothos-plugin-effect/blob/923ef4072cb5676c9564e1d7d09732a90ed1bdb2/packages/pothos-plugin-effect/src/e2e.test.ts#L233-L237

If `t.effect` works like this, is it sufficient in the case of using it with Drizzle?
