### ISSUE TITLE
Attempted import error: 'Cause'.'unannotate' is not exported from 'effect' (imported as 'Cause').

### ISSUE THREAD

**Issue by Enalmada** [iamchanii/pothos-plugin-effect#27]
I have been using pothos but I just discovered Effect. 

When I try to use `pothos-plugin-effect` with Effect v2.2.2 I get the error:
`Attempted import error: 'Cause'.'unannotate' is not exported from 'effect' (imported as 'Cause').`

I see `unannotate` being used on pothos-plugin-effect/src/field-builder.ts
```
function checkAndThrowResultIfFailure<E, A>(
  result: Exit.Exit<E, A>,
  FailErrorConstructor: { new(message: string): unknown } = Error,
): asserts result is Exit.Success<E, A> {
  // Check if result is a failure
  if (Exit.isFailure(result)) {
    const cause = Cause.unannotate(result.cause);
    ...
```

I don't seem to see Cause.unannotate being available in Effect v2.2.2.   I can't tell when it might have stopped being supported.  Could pothos-plugin-effect be updated to work with current version of Effect?  

I have attempted a PR here which makes build and tests pass.
https://github.com/iamchanii/pothos-plugin-effect/pull/28

Thanks for your help getting it reviewed and released so everyone can use the latest Effect version which everyone is going to get unless they explicitly specify something lower during install (which I don't think is practical since it doesn't match docs).

**Comment by iamchanii** [comment]
Unfortunately, I did write this library when Effect was in beta and I don't have been Effect in my code job nowadays. so I can't respond about which version is required as minimal as can use with this library.

**Comment by iamchanii** [comment]
Just wanted to let you know: I just started for 1.0 release. I will be rewriting code base and library then I'll take care of it.
