### ISSUE TITLE
Integration with the relay plugin

### ISSUE THREAD

**Issue by vecerek** [iamchanii/pothos-plugin-effect#3]
Hi there 👋 I'm just about to start using Effect in one of my existing projects and would love to try your plugin. One thing I noticed during the migration was that there's a missing integration with the [relay plugin](https://pothos-graphql.dev/docs/plugins/relay) that I use for declaring mutations like so:

```ts
builder.relayMutationField(
  "resourceCreate",
  {
    inputFields: (t) => ({
      a: t.string(),
    }),
  },
  {
    errors: {
      directResult: true,
      types: [
        FeatureUnavailableError,
        ForbiddenError,
        InvalidInputError,
        LimitReachedError,
      ],
    },
    resolve: async (_root, _args, _env) => ({
      resource: { /* blah blah blah */ },
    }),
  },
  {
    outputFields: (t) => ({
      resource: t.expose("resource", {
        nullable: false,
        type: "Resource",
      }),
    }),
  }
);
```

How would I write this mutation using the effect plugin?

**Comment by iamchanii** [comment]
I think I should implement new builder method for integration for relay plugin. At this time, I'm sorry about you can't do it. If you provide a reproducible repository, I would check it soon as faster.

**Comment by vecerek** [comment]
Hey @iamchanii, I've just created the following repository for you: [vecerek/pothos-plugin-effect-example](https://github.com/vecerek/pothos-plugin-effect-example). I've documented:

- how to run the server
- what example mutation you can run to get both a success and a failure
- how to re-generate the graphql schema file for comparison purposes to make sure the effect integration doesn't break it

If you have troubles running the project or anything else, just let me know 🙂

**Comment by vecerek** [comment]
@iamchanii so I [asked about this](https://github.com/hayes/pothos/issues/974) to learn more about the recommended ways of going about the problem. I've learned that using `relayMutationField` isn't really recommended, so I'll look into implementing mutations using the regular APIs, though which I think I should have access to the effect fields. I'll report back on how it went and will close the issue depending on the results.

**Comment by iamchanii** [comment]
Hey, @vecerek . I just release 0.7.0, so you can test `t.effectConnection` method from now. let me know it is enough for your purpose and feel free close issuse if you want.

https://github.com/iamchanii/pothos-plugin-effect/releases/tag/0.7.0

And thank you for your contribution and interest. this release wouldn't have been possible without your interest.
