### ISSUE TITLE
CJS support

### ISSUE THREAD

**Issue by vecerek** [iamchanii/pothos-plugin-effect#9]
@iamchanii, I've just migrated one of my projects over to ESM just so I could consume this plugin. However, not all my projects are in a state where such migration is straightforward. Would you consider also exporting a CJS build of the library?

**Comment by iamchanii** [comment]
Currently I'm not consider about CJS support. because is about efficiency. absolutely not difficult. I'm using nanobundle and I just should add 1 line for support CJS. but someday we, who loves or hates javascript ecosystem, have to use ESM as common.

**Comment by vecerek** [comment]
I totally respect that opinion.
